name: Deploy to Infinityfree via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    run-on: ubuntu-latest
    steps:
      - name: Get lastest code
        uses: actions/checkout@v4

      - name: Sync files to InfinityFree
        uses: Samkirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{{secrets.FTP_USERNAME}
          password: ${{secrets.FTP_PASSWORD}}
          port: 21
          server-dir: /htdocs/
          exclude: |
            **/ .git*
            **/ .git*/**
            **/node_modules/**
            .env
